// Code generated by 'goexports ./user'. DO NOT EDIT.

// +build go1.13,!go1.14

package main

import (
	"reflect"

	"github.com/mkevac/yaegitesting/user"
)

func init() {
	Symbols["github.com/mkevac/yaegitesting/user"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GenderFemale":                 reflect.ValueOf(user.GenderFemale),
		"GenderMale":                   reflect.ValueOf(user.GenderMale),
		"GenderMax":                    reflect.ValueOf(user.GenderMax),
		"GenderUnknown":                reflect.ValueOf(user.GenderUnknown),
		"GetRandomCustomParameter":     reflect.ValueOf(user.GetRandomCustomParameter),
		"GetRandomCustomParameterList": reflect.ValueOf(user.GetRandomCustomParameterList),
		"GetRandomGender":              reflect.ValueOf(user.GetRandomGender),
		"NewRandomUser":                reflect.ValueOf(user.NewRandomUser),

		// type definitions
		"CustomParameter": reflect.ValueOf((*user.CustomParameter)(nil)),
		"Gender":          reflect.ValueOf((*user.Gender)(nil)),
		"User":            reflect.ValueOf((*user.User)(nil)),
	}
}
